export const products = [
  {
    id: 1,
    img: "/clothing/kurti1.png",
    imgHover: "/clothing/kurti1-hover.png",
    title: "Green kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 2,
    img: "/clothing/kurti2.png",
    imgHover: "/clothing/kurti2-hover.png",
    title: "Red kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 3,
    img: "/clothing/kurti3.png",
    imgHover: "/clothing/kurti3-hover.png",
    title: "Yellow kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 4,
    img: "/clothing/kurti4.png",
    imgHover: "/clothing/kurti4-hover.png",
    title: "Blue kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 5,
    img: "/clothing/kurti5.png",
    imgHover: "/clothing/kurti5-hover.png",
    title: "Black kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 6,
    img: "/clothing/kurti6.png",
    imgHover: "/clothing/kurti6-hover.png",
    title: "White kurti",
    price: "Rs.1000",
    type: "ethnic",
  },
  {
    id: 7,
    img: "/clothing/white.png",
    imgHover: "/clothing/white-hover.png",
    title: "White dress",
    price: "Rs.1000",
    type: "western",
  },
  {
    id: 8,
    img: "/clothing/green.png",
    imgHover: "/clothing/green-hover.png",
    title: "Green dress",
    price: "Rs.2000",
    type: "western",
  },
  {
    id: 9,
    img: "/clothing/blue.png",
    imgHover: "/clothing/blueHover.png",
    title: "Blue dress",
    price: "Rs.2000",
    type: "western",
  },
  {
    id: 10,
    img: "/clothing/red.png",
    imgHover: "/clothing/red-hover.png",
    title: "Red dress",
    price: "Rs.1000",
    type: "western",
  },
  {
    id: 11,
    img: "/clothing/lgreen.png",
    imgHover: "/clothing/lgreen-hover.png",
    title: "Light Green dress",
    price: "Rs.1000",
    type: "western",
  },
  {
    id: 12,
    img: "/clothing/purple.png",
    imgHover: "/clothing/purple-hover.png",
    title: "Purple dress",
    price: "Rs.1000",
    type: "western",
  },
];
